Attempting to solve a vignette build issue
```R
> install_github('leekgroup/regionReport', build_vignettes = TRUE)
Downloading github repo leekgroup/regionReport@master
Installing regionReport
Skipping 9 packages not available: biovizBase, bumphunter, derfinder, derfinderPlot, GenomeInfoDb, GenomicRanges, ggbio, IRanges, TxDb.Hsapiens.UCSC.hg19.knownGene
Skipping 2 packages ahead of CRAN: ggplot2, knitrBootstrap
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD build  \
  '/private/var/folders/cx/n9s558kx6fb7jf5z_pgszgb80000gn/T/RtmpexuEd2/devtools9c25c34fe87/leekgroup-regionReport-252ee73'  \
  --no-resave-data --no-manual

* checking for file ‘/private/var/folders/cx/n9s558kx6fb7jf5z_pgszgb80000gn/T/RtmpexuEd2/devtools9c25c34fe87/leekgroup-regionReport-252ee73/DESCRIPTION’ ... OK
* preparing ‘regionReport’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Error in find_vignette_product(name, by = "weave", dir = docdir, engine = engine) :
  Failed to locate the ‘weave’ output file (by engine ‘utils::Sweave’) for vignette with name ‘bumphunterExampleOutput’. The following files exist in directory ‘/private/var/folders/cx/n9s558kx6fb7jf5z_pgszgb80000gn/T/RtmpOYuvQB/Rbuild9e827abaa732/regionReport/vignettes’: ‘Makefile’, ‘bumphunterExample.Rmd’, ‘bumphunterExample.html’, ‘bumphunterExampleOutput.Rmd’, ‘bumphunterReport-isolated.R’, ‘regionReport.R’, ‘regionReport.Rmd’, ‘regionReport.html’
Execution halted
Error: Command failed (1)
```

First, I forgot to specify the output directory to be the root one. Next, we'll
see if 'customCode' helps with adding the vignette html comment part.